In [2]:
import pandas as pd
import numpy as np

In [8]:
df = pd.read_excel('../2003-2023各省分行业全社会固定资产投资额.xlsx',sheet_name='总数据',index_col=[1,2])

In [14]:
df.loc[2003,'北京市']

id                         1.00
合计/亿元                   2169.26
农林牧渔业/亿元                  13.10
采矿业/亿元                     4.04
制造业/亿元                   190.55
电力、热力、燃气及水的生产和供应业/亿元      39.73
建筑业/亿元                    21.21
批发和零售业/亿元                 20.11
交通运输、仓储和邮政业/亿元           141.11
住宿和餐饮业/亿元                 23.08
信息传输、软件和信息技术服务业/亿元        85.98
金融业/亿元                     2.81
房地产业/亿元                 1223.61
租赁和商务服务业/亿元               29.57
科学研究和技术服务业/亿元             35.39
水利、环境和公共设施管理业/亿元         151.35
居民服务、修理和其他服务业/亿元           7.78
教育/亿元                     51.33
卫生和社会工作/亿元                16.48
文化、体育和娱乐业/亿元              33.15
公共管理、社会保障和社会组织/亿元         78.88
Name: (2003, 北京市), dtype: float64

In [22]:
file = '../data/trimpatent_all.csv'
patentdf = pd.read_csv(file)
patentdf['被引证次数'] = pd.to_numeric(patentdf['被引证次数'], errors="coerce").fillna(0).astype(int)

# patentdf.groupby(['申请人', '申请年份'])['被引证次数'].agg('sum').reset_index(name='被引证次数')
patentdf.to_csv(file,index=False)

/var/folders/zy/nptlsrmj6135ymrf1y08xr5r0000gn/T/ipykernel_52021/3439161184.py:2: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  patentdf = pd.read_csv(file)

In [3]:
patentdf = pd.read_excel('invest.xlsx',sheet_name='有专利公司首次投资')
a=patentdf['投资阶段']
a.unique()
# df = pd.read_csv('data/trimpatent_all.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'invest.xlsx'

In [5]:

investdf = pd.read_excel('../invest.xlsx',sheet_name='有专利公司首次投资')
a=investdf['投资阶段']
(a=='--').sum()/len(a)

np.float64(0.00035925992455541585)

In [6]:
(a=='--').sum()

np.int64(2)

In [6]:
df['专利类型'].value_counts()

专利类型
实用新型                    20501518
发明申请                    16314392
外观设计                     8062036
发明授权                     5135736
官网：www.macrodatas.cn          44
Name: count, dtype: int64

In [7]:
patent = pd.read_csv('中国专利数据库2005年.csv')
patent.head()

C:\Users\user\AppData\Local\Temp\ipykernel_1468\2097041834.py:1: DtypeWarning: Columns (34) have mixed types. Specify dtype option on import or set low_memory=False.
  patent = pd.read_csv('中国专利数据库2005年.csv')

,专利名称,专利类型,申请人,申请人类型,申请人地址,申请人地区,申请人城市,申请人区县,申请号,申请日,...,统一社会信用代码,引证次数,被引证次数,自引次数,他引次数,被自引次数,被他引次数,家族引证次数,家族被引证次数,Unnamed: 34
0,悬挂组合式自动燃气炉,发明授权,凌安国,个人,421002湖南省衡阳市江东区苗卜加树里84号衡阳铁路装卸机械厂劳动服务公司,中国,衡阳市,珠晖区,CN92109218.0,1992-08-01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN
1,一种前后用步双驱动自行车,发明授权,孟杰君; 梁秀芝,个人,157421黑龙江省宁安市东京城林业局职工医院手术室孟丽茹转,中国,牡丹江市,宁安市,CN92112099.0,1992-09-26,...,NaN,NaN,5.0,NaN,NaN,NaN,5.0,NaN,6.0,NaN
2,可用于游泳等的组合式流动液体槽,发明授权,许青,个人,100091北京市海淀区中央党校南院新2楼1单元202号许青,中国,北京市,海淀区,CN93103794.8,1993-04-22,...,NaN,2.0,7.0,NaN,2.0,7.0,NaN,3.0,7.0,NaN
3,山楂型核酸复合剂及其生产方法和用途,发明授权,杨秉渊; 王中侃; 戴连; 陈孝华; 林祥琼,个人,350011福建省福州市连江路福州二化宿舍17幢302室,中国,福州市,连江县,CN93103202.4,1993-03-16,...,NaN,1.0,NaN,1.0,NaN,NaN,NaN,1.0,NaN,NaN
4,人参黄芪型核酸复合剂及其生产方法,发明授权,杨秉渊; 王中侃; 戴连; 陈孝华; 林祥琼,个人,350011福建省福州市连江路福州二化宿舍17幢302室,中国,福州市,连江县,CN93103201.6,1993-03-16,...,NaN,1.0,NaN,1.0,NaN,NaN,NaN,1.0,2.0,NaN

In [8]:

patent['专利类型'].value_counts()

专利类型
实用新型                    81956
发明申请                    73826
外观设计                    70641
发明授权                    19739
官网：www.macrodatas.cn        1
Name: count, dtype: int64

In [ ]:
df

,专利名称,专利类型,申请人,申请人类型,申请人地址,申请人地区,申请人城市,申请人区县,申请号,申请日,...,统一社会信用代码,引证次数,被引证次数,自引次数,他引次数,被自引次数,被他引次数,家族引证次数,家族被引证次数,Unnamed: 34
0,悬挂组合式自动燃气炉,发明授权,凌安国,个人,421002湖南省衡阳市江东区苗卜加树里84号衡阳铁路装卸机械厂劳动服务公司,中国,衡阳市,珠晖区,CN92109218.0,1992-08-01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN
1,一种前后用步双驱动自行车,发明授权,孟杰君; 梁秀芝,个人,157421黑龙江省宁安市东京城林业局职工医院手术室孟丽茹转,中国,牡丹江市,宁安市,CN92112099.0,1992-09-26,...,NaN,NaN,5.0,NaN,NaN,NaN,5.0,NaN,6.0,NaN
2,可用于游泳等的组合式流动液体槽,发明授权,许青,个人,100091北京市海淀区中央党校南院新2楼1单元202号许青,中国,北京市,海淀区,CN93103794.8,1993-04-22,...,NaN,2.0,7.0,NaN,2.0,7.0,NaN,3.0,7.0,NaN
3,山楂型核酸复合剂及其生产方法和用途,发明授权,杨秉渊; 王中侃; 戴连; 陈孝华; 林祥琼,个人,350011福建省福州市连江路福州二化宿舍17幢302室,中国,福州市,连江县,CN93103202.4,1993-03-16,...,NaN,1.0,NaN,1.0,NaN,NaN,NaN,1.0,NaN,NaN
4,人参黄芪型核酸复合剂及其生产方法,发明授权,杨秉渊; 王中侃; 戴连; 陈孝华; 林祥琼,个人,350011福建省福州市连江路福州二化宿舍17幢302室,中国,福州市,连江县,CN93103201.6,1993-03-16,...,NaN,1.0,NaN,1.0,NaN,NaN,NaN,1.0,2.0,NaN

In [11]:
patent.columns

Index(['专利名称', '专利类型', '申请人', '申请人类型', '申请人地址', '申请人地区', '申请人城市', '申请人区县',
       '申请号', '申请日', '申请年份', '公开公告号', '公开公告日', '公开公告年份', '授权公告号', '授权公告日',
       '授权公告年份', 'IPC分类号', 'IPC主分类号', '发明人', '摘要文本', '主权项内容', '当前权利人',
       '当前专利权人地址', '专利权人类型', '统一社会信用代码', '引证次数', '被引证次数', '自引次数', '他引次数',
       '被自引次数', '被他引次数', '家族引证次数', '家族被引证次数', 'Unnamed: 34'],
      dtype='object')

In [2]:
a=3.0
type(a) == float

True

In [ ]:
df3 = pd.read_excel('govfund_filtered.xlsx')

基金分类
产业基金      1361
创业投资基金     559
--         299
PPP        186
Name: count, dtype: int64

In [20]:
df3['基金级别'].value_counts()

基金级别
地市级    939
区县级    744
省级     388
--     300
国家级     34
Name: count, dtype: int64